"""Application services for simulation orchestration."""

from agri_twin.application.clock import (
    ClockSource,
    MonotonicClockSource,
    SimulationClock,
    SimulationClockError,
    SimulationClockState,
    SimulationClockStateError,
    SimulationClockValueError,
)
from agri_twin.application.scheduler import (
    SimulationScheduler,
    SimulationSchedulerValueError,
)
from agri_twin.application.weather import WeatherEngine
from agri_twin.application.orchestrator import (
    CropDigitalTwinOrchestrator,
    CropSimulationError,
    CropSimulationSnapshot,
)
from agri_twin.application.scenarios import (
    Scenario,
    ScenarioComparison,
    ScenarioError,
    ScenarioEvent,
    ScenarioKind,
    ScenarioResult,
    ScenarioRunner,
    ScenarioSweepResult,
    compare_scenarios,
    sweep_scenarios,
)
from agri_twin.application.plot_weather import (
    build_crop_digital_twin_state,
    download_weather_for_plot,
)
from agri_twin.application.physical import (
    OpenFieldPhysicalModel,
    PhysicalEnvironmentModel,
    PhysicalEnvironmentResult,
    PhysicalModelError,
)
from agri_twin.application.providers import (
    ScenarioWeatherProvider,
    SyntheticWeatherProvider,
    WeatherProvider,
    WeatherProviderError,
    WeatherTimestampNotAvailable,
)
from agri_twin.application.synthetic_dataset import (
    SyntheticCropCycle,
    SyntheticDatasetError,
    SyntheticPlot,
    SyntheticReferenceDataset,
    SyntheticReferenceDatasetGenerator,
)
from agri_twin.application.multi_plot import (
    CropCycleState,
    CropCycleStatus,
    MultiPlotSimulation,
    MultiPlotSimulationResult,
    PlotSimulationResult,
)
from agri_twin.application.twin_state import (
    InMemoryTwinStateRepository,
    TwinSnapshot,
    TwinState,
    TwinStateConflict,
    TwinStateError,
    TwinStateRepository,
)
from agri_twin.application.twin_alignment import (
    AlignmentResult,
    AlignmentStatus,
    ComparisonDataset,
    ComparisonResult,
    CycleResolution,
    TemporalAlignment,
    compare_dataset,
    compare_observation,
)
from agri_twin.application.error_diagnostics import (
    ErrorDiagnostics,
    MetricSummary,
    OutlierReport,
    QualityCounts,
    diagnose,
)
from agri_twin.application.weather_configuration import (
    OpenMeteoSourceConfiguration,
    WeatherDatasetResult,
    WeatherConfigurationError,
    WeatherSourceConfiguration,
    create_offline_weather_provider,
    create_weather_provider_from_config,
    load_weather_source_configuration,
    build_open_meteo_client,
    build_open_meteo_request,
    download_weather_dataset_from_config,
)

__all__ = [
    "ClockSource",
    "MonotonicClockSource",
    "SimulationClock",
    "SimulationClockError",
    "SimulationClockState",
    "SimulationClockStateError",
    "SimulationClockValueError",
    "SimulationScheduler",
    "SimulationSchedulerValueError",
    "WeatherEngine",
    "CropDigitalTwinOrchestrator",
    "CropSimulationError",
    "CropSimulationSnapshot",
    "Scenario",
    "ScenarioComparison",
    "ScenarioError",
    "ScenarioEvent",
    "ScenarioKind",
    "ScenarioResult",
    "ScenarioRunner",
    "ScenarioSweepResult",
    "compare_scenarios",
    "sweep_scenarios",
    "download_weather_for_plot",
    "build_crop_digital_twin_state",
    "OpenFieldPhysicalModel",
    "PhysicalEnvironmentModel",
    "PhysicalEnvironmentResult",
    "PhysicalModelError",
    "ScenarioWeatherProvider",
    "SyntheticWeatherProvider",
    "WeatherProvider",
    "WeatherProviderError",
    "WeatherTimestampNotAvailable",
    "SyntheticCropCycle",
    "SyntheticDatasetError",
    "SyntheticPlot",
    "SyntheticReferenceDataset",
    "SyntheticReferenceDatasetGenerator",
    "CropCycleState",
    "CropCycleStatus",
    "MultiPlotSimulation",
    "MultiPlotSimulationResult",
    "PlotSimulationResult",
    "InMemoryTwinStateRepository",
    "TwinSnapshot",
    "TwinState",
    "TwinStateConflict",
    "TwinStateError",
    "TwinStateRepository",
    "AlignmentResult",
    "AlignmentStatus",
    "ComparisonDataset",
    "ComparisonResult",
    "CycleResolution",
    "TemporalAlignment",
    "compare_dataset",
    "compare_observation",
    "ErrorDiagnostics",
    "MetricSummary",
    "OutlierReport",
    "QualityCounts",
    "diagnose",
    "WeatherConfigurationError",
    "OpenMeteoSourceConfiguration",
    "WeatherDatasetResult",
    "WeatherSourceConfiguration",
    "create_offline_weather_provider",
    "create_weather_provider_from_config",
    "load_weather_source_configuration",
    "build_open_meteo_client",
    "build_open_meteo_request",
    "download_weather_dataset_from_config",
]
