"""Central MQTT topic catalogue."""


class Topics:
    SIMULATION_TIME = "agri/simulation/time"
    SIMULATION_CONTROL = "agri/simulation/control"
    SIMULATION_EVENTS = "agri/simulation/events"
    SIMULATION_STATUS = "agri/simulation/status"
    ENVIRONMENT_WEATHER = "agri/environment/weather"
    ENVIRONMENT_EVENTS = "agri/environment/events"
    ENVIRONMENT_DERIVED = "agri/environment/derived"
    STATE_CLIMATE = "agri/state/climate"
    STATE_SOIL = "agri/state/soil"
    STATE_CROP = "agri/state/crop"
    STATE_ACTUATORS = "agri/state/actuators"
    STATE_FULL = "agri/state/full"
    COMMAND_SHADE = "agri/commands/shade"
    COMMAND_WINDOWS = "agri/commands/windows"
    COMMAND_HVAC = "agri/commands/hvac"
    COMMAND_IRRIGATION = "agri/commands/irrigation"
    COMMAND_NATURAL_EVENT = "agri/commands/natural-event"
    SEMANTIC_CONTEXT = "agri/semantic/context"
    SEMANTIC_ALERTS = "agri/semantic/alerts"
    FAULT = "agri/events/fault"